### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by ndarilek** [hoodiehq/discussion#49]
I'd like to be able to attach files to documents. While storing binary data in the database isn't the greatest idea, I'm not sure of a more elegant solution for offline-first development. If I store a profile pic with my user account, an online-first service might store it in a CDN, but something like Hoodie would probably benefit from an API for storing and syncing document attachments. Maybe something like:
- hoodie.attach(id, filename, blob): Attach the specified blob to the specified ID with the specified filename (I don't recall if attachments also specify a MIME type)
- hoodie.attachments(id): Enumerate attachments for a given ID in the form {filename: blob, ...}
- hoodie.detach(id, filename): Remove the specified attachment from the specified ID

**Comment by gr2m** [comment]
Hello from 2+ years later 👋 Hoodie is using PouchDB now and you can add attachments. We don’t have a first-class API for it but we expose the current PouchDB instance at `hoodie.store.db`.

If anyone is still interested in this, then it would be great to create a guide on how to do attachments with Hoodie today, I’m happy to give guidance for that. 

But I’m going ahead and close this due to inactivity
